add ODY-235 説明カード実装
daydule/odyssey-frontend pull request #11
Opened 2023-10-14 00:59 UTC by Mellbrother

# 事前確認

-   [x] PR前に動作確認をしたか
-   [x] 機密情報を含んでいないか
-   [x] [開発ルール](https://daydule.atlassian.net/wiki/spaces/DAYDULE/pages/9765029)を守って実装しているか
-   [x] 単体テストが全てOKになっているか（単体テストを作成していないリポジトリの場合SKIP）
-   [x] 最新の`develop`ブランチを反映しているか
-   [x] ビルドエラー/ESLintエラーは起きていないか

# レビュワーによる動作確認

- [ ] @tom-takeru 
- [ ] @atoook 
- [ ] @kzk27 

# やったこと
説明カードの実装

# やらないこと
特になし

# 懸念点や注意点
特になし

# その他
特になし

2023-11-04 07:04 UTC, tom-takeru requested changes
コメントした！
確認お願い 🙏

2023-11-04 07:04 UTC, tom-takeru commented on src/components/forest/About.stories.tsx
> +    <div className='w-full  bg-about-page-image bg-cover bg-no-repeat py-10'>
この部分のスタイルは、Layoutコンポーネント的なやつに書くことになるやつ？
bg-about-page-imageはaboutページでのみ使われると思うんだけど、Aboutコンポーネント内に実装できたほうが良かったりしない？ 🐊

2023-11-04 07:04 UTC, tom-takeru commented on src/components/forest/About.stories.tsx
> +    <div className='w-full  bg-about-page-image bg-cover bg-no-repeat py-10'>
`w-full`の後ろにスペースが入ってる
```suggestion
    <div className='w-full bg-about-page-image bg-cover bg-no-repeat py-10'>
```
ESLintのTailwind　CSSのクラスの自動順序入れ変えとかってodysseyはまだ効いてないんだっけ？
dayduleでは自動で入れ替わったりしてこういうことは起きなそう

2023-11-04 07:04 UTC, tom-takeru commented on src/components/leaf/AboutCardWithImage.tsx
> +  // TODO: テキストが長すぎる時に枠を大きくする（画像の表示も変にならないようにする）
これレスポンシブ対応のチケットにも一応書いといた
https://daydule.atlassian.net/browse/ODY-276

2023-11-04 07:04 UTC, tom-takeru commented on src/components/forest/About.tsx
> +  const aboutCardsWithText = useMemo(() => {
useMemoあんまり分からなくて調べたんだけど、こことか、下の`aboutCardsWithImage`では使わなくてもいいんじゃない？
> Do Not Use useMemo With Empty Dependency List

[参考記事](https://www.perssondennis.com/articles/react-anti-patterns-and-best-practices-dos-and-donts#user-content-do-not-use-usememo-with-empty-dependency-list)


あと、この部分は「Time is Moneyとは」の下に表示される部分で、今後も複数になることはなさそうな気がする（aboutCardWithTextコンポーネントははタイトルとか持てないから連続で並ぶことはなさそう？）。
今後仮にそうなったとしても、その時に複数に対応できるようにすれば良い気がするんだけどどう？

2023-11-05 03:56 UTC, Mellbrother commented on src/components/forest/About.stories.tsx
> +    <div className='w-full  bg-about-page-image bg-cover bg-no-repeat py-10'>
About のpageで実装する

2023-11-05 03:56 UTC, Mellbrother commented on src/components/leaf/AboutCardWithImage.tsx
> +  // TODO: テキストが長すぎる時に枠を大きくする（画像の表示も変にならないようにする）
ありがとう

2023-11-11 04:40 UTC, Mellbrother commented on src/components/forest/About.tsx
> +  const aboutCardsWithText = useMemo(() => {
useMemo削除した

テキストのやつも1件にするように修正した

2023-11-11 04:41 UTC, Mellbrother commented on src/components/forest/About.stories.tsx
> +    <div className='w-full  bg-about-page-image bg-cover bg-no-repeat py-10'>
入れ替えは聞いてる、空白削除はしないらしい
気をつけるねー

2023-11-11 04:41 UTC, Mellbrother commented on src/components/forest/About.stories.tsx
> +    <div className='w-full  bg-about-page-image bg-cover bg-no-repeat py-10'>
修正済み

2023-11-12 00:35 UTC, tom-takeru approved these changes
🥍

2023-11-15 12:00 UTC, merged