🌲MainCardWithCommodityResult
daydule/odyssey-frontend pull request #12
Opened 2023-10-21 04:35 UTC by Mellbrother

# 事前確認

-   [x] PR前に動作確認をしたか
-   [x] 機密情報を含んでいないか
-   [x] [開発ルール](https://daydule.atlassian.net/wiki/spaces/DAYDULE/pages/9765029)を守って実装しているか
-   [x] 単体テストが全てOKになっているか（単体テストを作成していないリポジトリの場合SKIP）
-   [x] 最新の`develop`ブランチを反映しているか
-   [x] ビルドエラー/ESLintエラーは起きていないか

# レビュワーによる動作確認

- [ ] @tom-takeru 
- [ ] @atoook 
- [ ] @kzk27 

# やったこと
商品一覧を表示するメインカードの実装
商品が多い時はスクロールで閲覧するように実装

# やらないこと
特になし

# 懸念点や注意点
商品画像のborder-radiusがうまく効いていない気がするため、修正方法わかる人いれば教えてください
デザイン的に変というわけではないので、直らなそうであればそのままで

メインカードコンポーネントがマージされていないため、メインカードコンポーネント作成用のPRからブランチを切っています

# その他
特になし

2023-10-23 05:50 UTC, tom-takeru requested changes
コメントした！🐊

2023-10-23 05:50 UTC, tom-takeru commented on src/components/tree/MainCardWithCommodityResult.stories.tsx
> +export const ManyCommodity: Story = {
ManyCommodity→ManyCommodities

2023-10-23 05:50 UTC, tom-takeru commented on src/components/tree/MainCardWithCommodityResult.tsx
> +                price={commodity.price}
引数をCommodityオブジェクトにした方がスッキリしそう🐊

2023-10-23 05:50 UTC, tom-takeru commented on src/components/tree/MainCardWithCommodityResult.test.tsx
> +    const listItem = screen.getAllByRole('listitem');
ulにテストid振ってその子要素取得の方が良いとかある？
テストidってそんなにマストで使うってほどではないの？
テスト書いたことなくてわかんない

2023-10-23 05:50 UTC, tom-takeru commented on src/components/tree/MainCardWithCommodityResult.test.tsx
> +    expect(listItem.length).toBe(3);
3じゃなくてcommodities.lengthの方が厳密じゃない？🐊

2023-10-24 12:11 UTC, Mellbrother commented on src/components/tree/MainCardWithCommodityResult.test.tsx
> +    const listItem = screen.getAllByRole('listitem');
マストで使う必要ない
この要素取りたいけど、パッと取れないとかの時に使うことが多いかも

今回はliが取れれば良くて、getAllByRoleで簡単に取れたから使わなかった

2023-10-24 12:13 UTC, Mellbrother commented on src/components/tree/MainCardWithCommodityResult.test.tsx
> +    expect(listItem.length).toBe(3);
修正した

2023-10-24 12:13 UTC, Mellbrother commented on src/components/tree/MainCardWithCommodityResult.tsx
> +                price={commodity.price}
commodity引数にした

2023-10-24 12:13 UTC, Mellbrother commented on src/components/tree/MainCardWithCommodityResult.stories.tsx
> +export const ManyCommodity: Story = {
修正した

2023-10-26 08:50 UTC, tom-takeru approved these changes
🏖️

2023-11-08 11:25 UTC, merged