ODY-240 金額入力欄及び計算結果表示欄実装
daydule/odyssey-frontend pull request #13
Opened 2023-10-21 16:44 UTC by kzk27

# 事前確認

-   [x] PR前に動作確認をしたか
-   [x] 機密情報を含んでいないか
-   [x] [開発ルール](https://daydule.atlassian.net/wiki/spaces/DAYDULE/pages/9765029)を守って実装しているか
-   [ ] 単体テストが全てOKになっているか（単体テストを作成していないリポジトリの場合SKIP）
-   [ ] 最新の`develop`ブランチを反映しているか
-   [ ] ビルドエラー/ESLintエラーは起きていないか

# レビュワーによる動作確認

- [ ] @Mellbrother 
- [ ] @tom-takeru 
- [ ] @atoook 

# やったこと
- 以下のチケットをまとめて対応しました
  - ODY-222
  - ODY-240
  - ODY-227
  - ODY-234

# やらないこと
特になし

# 懸念点や注意点
特になし

# その他
特になし

2023-10-22 13:27 UTC, Mellbrother commented on src/components/leaf/Button.tsx
> +export default React.memo(Button);
https://qiita.com/soarflat/items/b9d3d17b8ab1f5dbfed2#%E3%81%AA%E3%81%9C-reactmemo-%E3%82%92%E5%88%A9%E7%94%A8%E3%81%99%E3%82%8B%E3%81%AE%E3%81%8B:~:text=%E3%82%92%E3%82%B9%E3%82%AD%E3%83%83%E3%83%97%E3%81%A7%E3%81%8D%E3%82%8B%E3%80%82-,%E3%81%AA%E3%81%9C%20React.memo%20%E3%82%92%E5%88%A9%E7%94%A8%E3%81%99%E3%82%8B%E3%81%AE%E3%81%8B,-%E4%BB%A5%E4%B8%8B%E3%81%AE%E3%82%88%E3%81%86

↑に記載の内容があっていれば、ここのボタンに関してはReact.memo使わなくても良いのかなと思ったのですが、いかがでしょうか？

2023-10-22 13:27 UTC, Mellbrother commented on src/app/main/page.tsx
>  // <Circle variant="orange"></Circle>
ここ残す意味あるんでしたっけ？

2023-10-22 13:27 UTC, Mellbrother commented on src/components/leaf/Input.tsx
> +  const inputType = (handleActive: React.Dispatch<React.SetStateAction<string>> | '') => {
型ですが、Props["handleActive"]という書き方もできるようですね
お手数ですが、どちらが良さそうか検討お願いできますでしょうか？

2023-10-22 13:27 UTC, Mellbrother commented on src/components/leaf/Input.tsx
> +          placeholder='入力してください'
placeholderはpropsで指定できるようにすることは不要でしょうか？

2023-10-22 13:27 UTC, Mellbrother commented on src/components/leaf/Input.tsx
> +          value={value || 0}
valueの初期値やtypeは汎用的に作らなくても良いでしょうか？
input.tsxというコンポーネントのため、他のバリエーションも使えるようにしておいた方が良いかなと思いました

2023-10-22 13:27 UTC, Mellbrother commented on src/components/leaf/Input.tsx
> +          value={value || 0}
今回のものに特化する場合は、コンポーネント名を変えても良いかなと思いました

2023-10-22 13:27 UTC, Mellbrother commented on src/components/leaf/Input.tsx
> +  handleChange: React.Dispatch<React.SetStateAction<number>>;
handleChangeとhandleActiveとしてどのような関数を求めているかコメントに記載お願いできますでしょうか？

2023-10-22 13:27 UTC, Mellbrother commented on src/components/forest/Main.tsx
> +// <Circle variant="orange"></Circle>
こちらのコメント必要ですか？

2023-10-22 13:27 UTC, Mellbrother commented on src/components/tree/MainCardWithInput.tsx
> +          monthlyIncomeData = changeState / 12;
定数系はどこかのファイルにまとめたいですね
12とか173とか

2023-10-22 13:27 UTC, Mellbrother commented on src/components/tree/MainCardWithInput.tsx
> +          monthlyIncomeData = changeState * 173;
monthlyIncomeでいいかなと思いました
他も同様

2023-10-22 13:27 UTC, Mellbrother commented on src/components/tree/MainCardWithInput.tsx
> +  const [changeState, setChangeState] = useState<number>(0);
名前から何の値が想像しにくいのかなと思いました
確かに変更された値なのですが、収入関連の値であることもわかるようにしたいです

2023-10-22 13:27 UTC, Mellbrother commented on src/components/tree/MainCardWithInput.tsx
> +          monthlyIncomeData = changeState / 12;
年収などの文字列も判定に使うのであれば、定数かの方がいいかなと思いました（表示だけであれば、不要かと思いますが。。）

2023-10-22 13:27 UTC, Mellbrother commented on src/components/tree/MainCardWithInput.tsx
> +  const isFirstRender = useNotInitializingEffect();
これ、なぜやっているかコメントお願いできますでしょうか？

2023-10-22 13:27 UTC, Mellbrother commented on src/components/tree/MainCardWithMoneyResult.tsx
> +      const previousPriceData = Number(localStorage.getItem('previousPrice'));
previousPriceで良いかと思いました
differenceも同様

2023-10-22 14:01 UTC, Mellbrother commented on src/components/tree/MainCardWithInput.tsx
> +          monthlyIncomeData = changeState * 173;
あ、useStateの定義と被るのか。。。
ここなしで

2023-10-22 14:01 UTC, Mellbrother commented on src/components/tree/MainCardWithMoneyResult.tsx
> +      const previousPriceData = Number(localStorage.getItem('previousPrice'));
useStateの定義と被るのか。。。
ここなしで

2023-10-24 14:31 UTC, kzk27 commented on src/components/leaf/Button.tsx
> +export default React.memo(Button);
Buttonコンポーネントの親であるMainCardWithInputでは、Input要素に値が入力されるたび（onChangeのたび）に再レンダリングされる仕様になっております。
これはInputで入力した値（ex. 年収フォーム）を別のInput（ex. 時給フォーム）にも反映させるために必要な処理なのですが、Buttonコンポーネントについては再レンダリングを行わなくても良いコンポーネントになるのでメモ化しています🙏

なので、記事の内容でいくと「頻繁に再レンダリングされるコンポーネント内の子コンポーネント」に該当するかと思うのですがいかがでしょうか？🙇

2023-10-24 14:32 UTC, kzk27 commented on src/app/main/page.tsx
>  // <Circle variant="orange"></Circle>
動作確認用に残していたのですが、pageファイルなしで動作確認ってどのようにすれば良いんでしたっけ？🙏

2023-10-24 14:34 UTC, kzk27 commented on src/components/leaf/Input.tsx
> +  const inputType = (handleActive: React.Dispatch<React.SetStateAction<string>> | '') => {
@Mellbrother 
なるほど！
その指定方法の方がスマートなので修正しておきます🙏

2023-10-24 14:35 UTC, kzk27 commented on src/components/leaf/Input.tsx
> +          placeholder='入力してください'
@Mellbrother 
汎用性高めるために実装しておきます！

2023-10-24 14:39 UTC, kzk27 commented on src/components/leaf/Input.tsx
> +          value={value || 0}
@Mellbrother 
今回作成したInputはかなり特殊な実装なので、基本的にMainCardの情報入力欄でしか利用できないと思います。
なので、ファイル名を変更する対応でいきたいと思います🙏

2023-10-24 14:45 UTC, kzk27 commented on src/components/leaf/Input.tsx
> +  handleChange: React.Dispatch<React.SetStateAction<number>>;
@Mellbrother 
コメント記載しておきました🙏

2023-10-24 14:45 UTC, kzk27 commented on src/components/forest/Main.tsx
> +// <Circle variant="orange"></Circle>
@Mellbrother 
不要なので削除しました。

2023-10-24 14:58 UTC, kzk27 commented on src/components/tree/MainCardWithInput.tsx
> +          monthlyIncomeData = changeState / 12;
定数ファイル作成して対応します！

2023-10-24 15:05 UTC, kzk27 commented on src/components/tree/MainCardWithInput.tsx
> +  const [changeState, setChangeState] = useState<number>(0);
「収入（年収・月給・時給）入力値」に修正しました。

2023-10-24 15:08 UTC, kzk27 commented on src/components/tree/MainCardWithInput.tsx
> +  const isFirstRender = useNotInitializingEffect();
コメントを追記しました。

2023-10-31 13:14 UTC, Mellbrother commented on src/components/leaf/Button.tsx
> +export default React.memo(Button);
なるほど
であれば問題ないと思います

2023-10-31 13:15 UTC, Mellbrother commented on src/app/main/page.tsx
>  // <Circle variant="orange"></Circle>
@kzk27 
コメントの話です〜

2023-10-31 13:16 UTC, Mellbrother commented on src/app/main/page.tsx
>  // <Circle variant="orange"></Circle>
削除されていたのでResolve

2023-10-31 13:20 UTC, Mellbrother commented
@kzk27 
[src/components/leaf/MainCardInput.test.tsx](https://github.com/daydule/odyssey-frontend/pull/13/files#diff-3f7a7e7aa324ac1426d4457d6d34acacec5a0e73dd4ab23c4bd10e7cc543c516)

これ、なんで空なんでしたっけ？
他で担保できている状態でしたら、ファイル削除お願いします

2023-10-31 13:24 UTC, Mellbrother commented on src/components/tree/MainCardWithInput.tsx
> +  const [changeState, setChangeState] = useState<number>(0);
@kzk27 
変数名も変えたりできそうです？？

2023-10-31 13:26 UTC, Mellbrother commented
@kzk27 
CI失敗しているので、修正お願いします

2023-11-04 05:41 UTC, tom-takeru requested changes
コメントしました！
ビルドエラーも含めて確認をおねがいします　🙇

2023-11-04 05:41 UTC, tom-takeru commented on src/hooks/useNotInitializingEffect.tsx
> +};
これって何か参考にしたんですか？

2023-11-04 05:41 UTC, tom-takeru commented on src/components/leaf/MainCardInput.tsx
> +  handleActive: React.Dispatch<React.SetStateAction<string>> | ''; // ユーザーが現在アクティブ状態にしているフォームを特定するためのSet関数が入る
handleActiveのtypeとして空文字を許容していることに違和感がありました。
handleActiveが空文字かどうかでreturn文が分岐していますが、アクティブかどうかは別のプロパティで持たせておくのはどうでしょうか？ 🐊

2023-11-04 05:41 UTC, tom-takeru commented on src/components/tree/MainCardWithInput.tsx
> +  const [active, setActive] = useState<string>(CONSTANT.LABEL.ANNUAL_INCOME);
これって全てアクティブではないこともありで良い気がするのですがどうでしょうか？ 🐊

2023-11-04 05:41 UTC, tom-takeru commented on src/components/tree/MainCardWithInput.tsx
> +  const [active, setActive] = useState<string>(CONSTANT.LABEL.ANNUAL_INCOME);
別件：コメントは消してしまって、変数名を`activeInput`などとするのはどうでしょうか？

2023-11-04 05:41 UTC, tom-takeru commented on src/components/forest/Main.tsx
> +export const SetMainPriceContext = createContext({} as SetMainPriceContext);
↓こんな感じで1つのコンテキストで管理するのはどうでしょうか？ 🐊 

```
〜略〜
type MainPriceContextType = {
  mainPrice: number;
  setMainPrice: React.Dispatch<React.SetStateAction<number>>;
};

export const MainPriceContext = createContext({} as MainPriceContextType);

const Main = () => {
  const [mainPrice, setMainPrice] = useState<number>(0);

  return (
    <MainPriceContext.Provider value={{ mainPrice, setMainPrice }}>
      <div className='flex min-h-screen items-center justify-center bg-gray-100'>
        <MainCardWithInput />
        <MainCardWithMoneyResult />
      </div>
    </MainPriceContext.Provider>
  );
};
〜略〜
```

2023-11-12 05:14 UTC, kzk27 commented on src/components/tree/MainCardWithInput.tsx
> +  const [changeState, setChangeState] = useState<number>(0);
ユーザーが現在入力している値を受け取るので「currentInput」に変更しました🙏

2023-11-12 05:23 UTC, kzk27 commented on src/components/tree/MainCardWithInput.tsx
> +  const [active, setActive] = useState<string>(CONSTANT.LABEL.ANNUAL_INCOME);
ユーザーが現在入力している値を受け取るので「currentInput」に変更しました🙏

2023-11-12 05:33 UTC, kzk27 commented on src/components/forest/Main.tsx
> +export const SetMainPriceContext = createContext({} as SetMainPriceContext);
Stateとセット関数を同じプロバイダーに持たせるとmainPriceが変更されることでsetMainPriceしか参照していないコンポーネントも再レンダリングされてしまうので分けて記載しております🙏
（FYI：[正しく使うReactContext](https://zenn.dev/yuta_ura/articles/react-context-api#%E3%82%A2%E3%83%B3%E3%83%81%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3-1.-%E5%80%A4%E6%9C%AC%E4%BD%93%E3%81%A8%E5%80%A4%E3%82%92%E5%85%A5%E3%82%8C%E3%82%8B%E9%96%A2%E6%95%B0%E3%82%92-1-%E3%81%AE-context-%E3%81%AB%E5%85%A5%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B)）

ただ、現在のコードだとProviderに直接コンポーネントを渡しているので、上記の修正をしても全てのコンポーネントが再レンダリングされますね。。。

コンポジション使った書き方に修正しておきます！

2023-11-12 14:55 UTC, kzk27 commented on src/hooks/useNotInitializingEffect.tsx
> +};
初回時にuseEffectが走ると無駄な計算処理が走ってしまうのでそれらを防止するために実装しました！
処理の記述方法としては[こちらの記事](https://zenn.dev/catnose99/scraps/30c623ba72d6b5)を参考に実装しました🙏

2023-11-12 15:34 UTC, kzk27 commented on src/components/tree/MainCardWithInput.tsx
> +  const [active, setActive] = useState<string>(CONSTANT.LABEL.ANNUAL_INCOME);
> これって全てアクティブではないこともありで良い気がするのですがどうでしょうか？ 🐊
ご指摘通りだったので修正しました！

> 別件：コメントは消してしまって、変数名をactiveInputなどとするのはどうでしょうか？
反映しました🙏

2023-11-12 15:36 UTC, kzk27 commented on src/components/leaf/MainCardInput.tsx
> +  handleActive: React.Dispatch<React.SetStateAction<string>> | ''; // ユーザーが現在アクティブ状態にしているフォームを特定するためのSet関数が入る
おっしゃる通りから文字許容は違和感あるので、修正しました！
プロパティを追加せずにhandleActiveをオプショナルにすることで解消しましたが、問題ないでしょうか？？

2023-11-13 01:17 UTC, tom-takeru commented on src/components/leaf/MainCardInput.tsx
> +    if (handleActive) {
### 会議の議題

handleActiveにisActiveの責務も持たせるのはありか？

2023-11-13 01:49 UTC, tom-takeru reviewed
一件だけ会議で話したいです！

2023-11-28 00:34 UTC, tom-takeru commented on src/components/leaf/MainCardInput.tsx
> +    if (handleActive) {
「`isActive`propsを作ったほうが可読性も上がり、propsごとの責務も明確になるので良い」と会議で結論が出ました。
そのようにお願いします🙏

- [ ] `isActive` Propsを追加

2023-11-28 14:23 UTC, kzk27 commented on src/components/leaf/MainCardInput.tsx
> +    if (handleActive) {
@tom-takeru 
handleActiveはisActiveの責務のみを持ったStateとして作成している認識です。
なので、isActive Propsを新規で作成するという結論はどのような責務分けを想定しての結論か教えていただくことはできますでしょうか？🙇

2023-11-28 23:37 UTC, tom-takeru commented on src/components/leaf/MainCardInput.tsx
> +    if (handleActive) {
@kzk27 
私の認識では`handleActive`は以下の2つの責務を持っているのでは？という認識です。

- `MainCardInput`がアクティブかどうか？
  - その役割を果たしている実装：15行目
- `MainCardInput`コンポーネントがクリックされた時どのように処理するのか？
  - その役割を果たしている実装：28行目

私からの案としては、

- `handleActive`Propsを削除
- `handleClick?　: () => void`Propsを追加
  - 呼び出し元で`handleClick={() => setActive(label)}`として実装
- `isActive: boolean`Propsを追加

2023-12-02 10:39 UTC, kzk27 commented on src/components/leaf/MainCardInput.tsx
> +    if (handleActive) {
前回会議でhandleClickを任意の関数にするのは汎用性が広がりすぎてしまうといった結論になったかと思うのでhandleClickに入るものは`React.Dispatch<React.SetStateAction<string>>`のままにし、PropsにisActiveを追加する処理を実装しました。

認識違いなどありましたらご指摘いただけると助かります🙇

2023-12-03 08:00 UTC, tom-takeru reviewed
コメントしました！
最初のレビューで気づかなかったものもあり、すみません 🙏

2023-12-03 08:00 UTC, tom-takeru commented on src/components/leaf/MainCardInput.tsx
> +  handleClick?: React.Dispatch<React.SetStateAction<string>>; // ユーザーが現在アクティブ状態にしているフォームを特定するためのSet関数が入る
（ただのメモ）
[記事「（メモ）Reactコンポーネントアンチパターン」](https://zenn.dev/link/comments/d9e485a0aa820f)が正しいのかは分かりませんが、主張は理解できます。
今後も情報を集めて、判断しましょう！

2023-12-03 08:00 UTC, tom-takeru commented on src/components/leaf/MainCardInput.stories.tsx
> +    handleClick: undefined,
ストーリーも`isActive`Props追加による更新をお願いします！

- [x] MainCardInputのストーリーを修正

2023-12-03 08:00 UTC, tom-takeru commented on src/components/leaf/MainCardInput.stories.tsx
> +  title: 'Leaf/Input',
すみません、今気づきました！
```suggestion
  title: 'Leaf/MainCardInput',
```
OKなら　`Commit suggestion`ボタンでマージをお願いします！
（その後ローカル作業する場合はpullも忘れずに！）

2023-12-03 08:00 UTC, tom-takeru commented on src/components/leaf/MainCardInput.tsx
> +    } else {
`isActive === true`かつ`handleActive`が`undifined`の場合（この使い方をされることはない認識ですが）は、「onClickでは何もしなくて良い」という意味になると思いました🐊
もし、「onClickでは何もしなくて良い」の使い方はしないで！という意思を込める場合は、`return;`だと不親切なように見えます。

こんな型の書き方があるらしいのですがどうでしょうか。（ちょっと認知負荷は高いですが、、、）
（`optionalProp`に関して`isEnable`が、`true`の時は`string`、`false`のときは`string | undefined`）

```
type MyComponentProps = {
    isEnable: boolean;
} & (true extends MyComponentProps['isEnable'] ? { optionalProp: string } : { optionalProp?: string });
```

それか、「onClickでは何もしなくて良い」の使い方OK かつ 「ネストを減らして可読性を上げる」という意味で以下でどうでしょうか？（こっちを推します）
`onClick={() => handleClick && handleClick(label)}`として`handleClick`が`undefined`の時は何もしないようにしています。

```suggestion
    if (isActive) {
      return (
        <div className='flex'>
          <input
            disabled={true}
            className='text-right outline-none placeholder:text-gray-700'
            onChange={onChange}
            value={value || 0}
            placeholder={value ? String(value) : '入力値'}
            id={label}
            type='tel'
          />
          <svg
            onClick={() => handleClick && handleClick(label)}
            xmlns='http://www.w3.org/2000/svg'
            width='20'
            height='20'
            viewBox='0 0 20 20'
            fill='none'
          >
            <path d='M15 0L12.5 2.5L17.5 7.5L20 5L15 0ZM10 5L0 15V20H5L15 10L10 5Z' fill='#D3D3D3' />
          </svg>
        </div>
      );
    } else {
```

2023-12-10 23:02 UTC, kzk27 commented on src/components/leaf/MainCardInput.stories.tsx
> +    handleClick: undefined,
修正します🙏

2023-12-14 00:15 UTC, tom-takeru approved these changes
LGTM 👏

2023-12-14 00:15 UTC, merged